""" a = {{"isbn":isbn_},
    {"title":title_},
    {"author":author_},
    {"author_a":author_a_},
    {"publishhouse_id":publishhouse_id_},
    {"publishdate":publishdate_},
    {"booksize_id":booksize_id_},
    {"country_id":country_id_},
    {"language_id":language_id_},
    {"subjecttype_id":subjecttype_id_},
    {"type_id":type_id_},
    {"brief":brief_},
    {"cover_photoalbum":cover_photo_},
    {"album":''},
    {"price":price_},
    {"price_unit":price_unit_},
    {"pages":pages_},
    {"volume_total":volume_total_},
    {"volume_id":volume_id_},
    {"sets_id":sets_id_},
    {"sets_localid":sets_localid_},
    {"add_time":add_time_},
    {"memo":memo_},
    {"class_id":class_id_},
    {"age":age_},
    {"keywords":keywords_},
    {"update_time":update_time_},
    {"update_uid":update_uid_},
    {"update_nickname":update_nickname_},
    {"title_PinYin":title_PinYin_},
    {"tst_flag":tst_flag_},
    {"book_src_id":book_src_id_},
    {"catalogue":catalogue_},
    {"authorinfo":authorinfo_},
    {"data_src_flag":data_src_flag_},
    {"country":country_},
    {"updatetime":updatetime_},
    {"bookbrand_id":bookbrand_id_},
    {"editor_recommend":editor_recommend_},
    {"content_recommend":content_recommend_},
    {"media_reviews":media_reviews_},
    {"preface":preface_},
    {"digest":digest_},
    {"sub_title":sub_title_},
    {"tst_keywords":tst_keywords_},
    {"isbn_flag":isbn_flag_},
    {"bookprize":bookprize_},
    {"guid":guid_},
    {"hq_flag":hq_flag_},
    {"verify_flag":verify_flag_},
    {"fun_question":fun_question_},
    {"reading_guide":reading_guide_},
    {"brand":brand_},
    {"cover_photo_custom":cover_photo_custom_},
    {"tst_scope":tst_scope_},
    {"super_audit_flag":super_audit_flag_},
    {"clock_in_num":clock_in_num_},
    {"lend_count":lend_count_},
    {"one_word":one_word_},
    {"top_recommend":top_recommend_},
    {"authorinfo_text":authorinfo_text_},
    {"brief_text":brief_text_}} """
a = {"isbn":10996375},{"title":"动物王国大探秘（平）：全4册（京东专供.）"},{"author":"author"},{"author_a":"author_english"},{"author_a":"author_english"},{"publishhouse_id":''},{"publishdate":''},{"booksize_id":''},{"country_id":''},{"language_id":''},{"subjecttype_id":"书的尺寸"},{"type_id":0},{"brief":"图书分类"},{"cover_photo":''},{"album":''},{"price":0},{"price_unit":"RMB"},{"pages":''},{"volume_total":''},{"volume_id":''},{"sets_id":''},{"sets_localid":0},{"add_time":"2017-09-2509:11:30"},{"memo":''},{"class_id":0},{"age":''},{"keywords":"测试"},{"update_time":"2018-01-2615:28:13"},{"update_uid":''},{"update_nickname":"kali@neobv.com2"},{"title_PinYin":"DWWGDTMPQ4CJDZG."},{"tst_flag":0},{"data_src_flag":2},{"book_src_id":''},{"catalogue":''},{"authorinfo":''},{"data_src_flag":2},{"country":''},{"updatetime":"2020-10-1212:50:09"},{"bookbrand_id":''},{"editor_recommend":''},{"content_recommend":''},{"media_reviews":''},{"preface":''},{"digest":''},{"sub_title":''},{"tst_keywords":''},{"isbn_flag":0},{"bookprize":''},{"guid":''},{"hq_flag":0},{"verify_flag":0},{"fun_question":''},{"reading_guide":''},{"brand":''},{"cover_photo_custom":''},{"tst_scope":0},{"super_audit_flag":0},{"clock_in_num":0},{"lend_count":0},{"one_word":''},{"top_recommend":''},{"authorinfo_text":''},{"brief_text":''} 
# a = {{"isbn":10996375},
# {"title":"动物王国大探秘（平）：全4册（京东专供.）"},
# {"author":"author"},
# {"author_a":"author_english"},
# {"author_a":"author_english"},
# {"publishhouse_id":''},
# {"publishdate":''},
# {"booksize_id":''},
# {"country_id":''},
# {"language_id":''},
# {"subjecttype_id":"书的尺寸"},
# {"type_id":0},
# {"brief":"图书分类"},
# {"cover_photo":''},
# {"album":''},
# {"price":0},
# {"price_unit":"RMB"},
# {"pages":''},
# {"volume_total":''},
# {"volume_id":''},
# {"sets_id":''},
# {"sets_localid":0},
# {"add_time":"2017-09-2509:11:30"},
# {"memo":''},
# {"class_id":0},
# {"age":''},
# {"keywords":"测试"},
# {"update_time":"2018-01-2615:28:13"},
# {"update_uid":''},
# {"update_nickname":"kali@neobv.com2"},
# {"title_PinYin":"DWWGDTMPQ4CJDZG."},
# {"tst_flag":0},{"data_src_flag":2},
# {"book_src_id":''},
# {"catalogue":''},
# {"authorinfo":''},
# {"data_src_flag":2},
# {"country":''},
# {"updatetime":"2020-10-1212:50:09"},
# {"bookbrand_id":''},
# {"editor_recommend":''},
# {"content_recommend":''},
# {"media_reviews":''},
# {"preface":''},
# {"digest":''},
# {"sub_title":''},
# {"tst_keywords":''},
# {"isbn_flag":0},
# {"bookprize":''},
# {"guid":''},
# {"hq_flag":0},
# {"verify_flag":0},
# {"fun_question":''},
# {"reading_guide":''},
# {"brand":''},
# {"cover_photo_custom":''},
# {"tst_scope":0},
# {"super_audit_flag":0},
# {"clock_in_num":0},
# {"lend_count":0},
# {"one_word":''},
# {"top_recommend":''},
# {"authorinfo_text":''},
# {"brief_text":''}}

for b in a:
    # print(b)
    for key,value in b.items():
        print("\"",key,"\"")




